<a href="https://colab.research.google.com/github/NairaAhmed00/NairaAhmed00/blob/main/DEPI.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

import numpy as np

# 1. Broadcasting
# a) Add a 1D array [1, 2, 3] to each row of a 2D array [[10, 20, 30], [40, 50, 60]].
# Expected: [[11, 22, 33], [41, 52, 63]]

# b) Multiply a 2D array [[1, 2], [3, 4]] by a 1D array [10, 20] column-wise.
# Expected: [[10, 20], [60, 80]]

# 2. Indexing and Slicing (High Dimensional Arrays)
arr = np.arange(1, 25).reshape(2, 3, 4)

# a) Extract the second slice along axis 0.
# Expected: [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]

# b) Extract all rows and the last column for all slices.
# Expected: [[4, 8, 12], [16, 20, 24]]

# c) Reverse the order of slices along axis 0.
# Expected: [[[13, 14, 15, 16], ...], [[1, 2, 3, 4], ...]]

# d) Set all even elements in the array to -1.
# Expected: All even numbers replaced by -1.

# 3. np.repeat
# a) Given arr = np.array([1, 2, 3, 4, 5, 6]), create a new array where every odd element is repeated twice.
# Expected: [1, 1, 3, 3, 5, 5]

# b) Given arr = np.array([1, 2, 3, 4, 5, 6]), create a new array where elements are repeated based on their value.
# For example, 1 is repeated once, 2 twice, etc.
# Expected: [1, 2, 2, 3, 3, 3, 4, 4, 4, 4, ...]

# 4. Normalizing
# a) Normalize a 1D array arr = np.array([10, 20, 30]) to have values between 0 and 1.
# Expected: [0.0, 0.5, 1.0]

# 5. Bonus Challenge
# a) Create a 3x3 matrix where each element at position (i, j) is i * j.
# Expected: [[0, 0, 0], [0, 1, 2], [0, 2, 4]]

# b) Given a 4x4 matrix, replace all elements on the main diagonal with 0 without using a loop.
# Expected: Diagonal elements replaced with 0.




In [2]:
import numpy as np

In [5]:
arr_2d = np.array([[10, 20, 30], [40, 50, 60]])
arr_1d = np.array([1, 2, 3])

result = arr_2d + arr_1d
result

array([[11, 22, 33],
       [41, 52, 63]])

In [7]:
arr_2d = np.array([[1, 2], [3, 4]])
arr_1d = np.array([10, 20])

result = arr_2d * arr_1d[:, np.newaxis]
result

array([[10, 20],
       [60, 80]])

In [10]:
arr = np.arange(1, 25).reshape(2, 3, 4)
second_slice = arr[1]
print(second_slice)

[[13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]


In [11]:
last_column = arr[:, :, -1]
print(last_column)

[[ 4  8 12]
 [16 20 24]]


In [12]:
reversed_slices = arr[::-1]
print(reversed_slices)

[[[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]

 [[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]


In [15]:
arr[arr % 2 == 0] = -1
print(arr)

[[[ 1 -1  3 -1]
  [ 5 -1  7 -1]
  [ 9 -1 11 -1]]

 [[13 -1 15 -1]
  [17 -1 19 -1]
  [21 -1 23 -1]]]


In [16]:
arr = np.array([1, 2, 3, 4, 5, 6])
repeated_arr = np.repeat(arr, np.where(arr % 2 != 0, 2, 1))
print(repeated_arr)

[1 1 2 3 3 4 5 5 6]


In [17]:
arr = np.array([1, 2, 3, 4, 5, 6])
repeated_arr = np.repeat(arr, arr)
print(repeated_arr)

[1 2 2 3 3 3 4 4 4 4 5 5 5 5 5 6 6 6 6 6 6]


In [18]:
arr = np.array([10, 20, 30])
normalized_arr = (arr - arr.min()) / (arr.max() - arr.min())
print(normalized_arr)

[0.  0.5 1. ]


In [19]:
matrix = np.fromfunction(lambda i, j: i * j, (3, 3), dtype=int)
print(matrix)

[[0 0 0]
 [0 1 2]
 [0 2 4]]


In [20]:
matrix = np.arange(16).reshape(4, 4)
np.fill_diagonal(matrix, 0)
print(matrix)

[[ 0  1  2  3]
 [ 4  0  6  7]
 [ 8  9  0 11]
 [12 13 14  0]]
